services:
  db:
    image: mysql:8.0
    container_name: canim_ecommerce_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: canim_ecommerce
    ports:
      - "3307:3306"             
    volumes:
      - db_data:/var/lib/mysql
      - ./db/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

 